In [1]:
import numpy as np

In [5]:
# Start of with Indexing and slicing
# (1) Indexing - Similar to List in python
arr1=np.array([1,2,3])
arr1[0:2]

array([1, 2])

In [11]:
# We can print array in reverse
arr1[::-1]

array([3, 2, 1])

In [13]:
# We can also do reverse indexing
arr1[-2]

np.int64(2)

In [16]:
# Lets try indexing in 2D array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2[0,2]

np.int64(3)

In [20]:
# (2) Slicing in 2D
arr2[0:3,0]

array([1, 4, 7])

In [23]:
# Suppose in the last row we need to select 8 use slicing then
arr2[-1,1:2]

array([8])

In [25]:
# Reverse 2D array
arr2[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [28]:
# Now i want [1,2], [4,5] and [7,8]
arr2[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [30]:
# Now Lets see iteration on Array
for row in arr2:
  print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [35]:
# Flat method
for cell in arr2.flat:
  print(cell,end=",")

1,2,3,4,5,6,7,8,9,

In [38]:
# Stacking 2 Arrays
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[7,8],[9,10],[11,12]])
# (1) Vertical Stacking
c=np.vstack((a,b))
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [40]:
# (2) Horizontal Stacking
d=np.hstack((a,b))
d

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [45]:
# Splitting an Array
a1=np.arange(30).reshape(2,15)
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [54]:
# (1) Horizontal Split
np.hsplit(a1,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [56]:
# (2) Vertical Split
np.vsplit(a1,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [58]:
# Indexing with boolean arrays
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
# Getting True/False based on Conditions
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
# Now Do indexing with boolean array which is b
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [69]:
# Indexing with boolean also useful if we want to replace True values with ceratin numbers
a[b]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])