In [4]:
import numpy as np

In [5]:
# Create 1D array and access it
arr=  np.array([1,2,3,4,5])
print(arr[2])

3


In [6]:
# Create 2D array and access it
arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
# To access 5th number then
print(arr2[1,1])

5


In [8]:
# Properties
# (1) ndim - tells which dimensional is the array
arr2.ndim

2

In [10]:
# (2) itemsize - tells how much byte of items are there in the array
arr2.itemsize

8

In [12]:
# Data Type of arr2 each element in google colab is 8 byte or (64 bits) beacuse google colab running on 64-bit architecutre
arr2.dtype

dtype('int64')

In [44]:
# To change dtype
arr3=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
arr3.itemsize

8

In [48]:
# shape - Give the info about the 2D array
arr3.shape

(2, 3)

In [50]:
# Lets make complex number instead of float
arr4=np.array([[1,2,3],[4,5,6]],dtype=np.complex64)
arr4

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [58]:
# Now lets initialise array with placeholder number lets i want to make 2D just by 0 number and wanted to make a 2D array (ones and zeros exist)
arr4=np.ones((2,2),dtype=np.int64)
arr4

array([[1, 1],
       [1, 1]])

In [60]:
# In numpy arange exist instead of range in python
arr5=np.arange(1,6)
arr5

array([1, 2, 3, 4, 5])

In [66]:
# In arange there is step argument also which means each iteration number have a step example
arr6=np.arange(2,11,2)
arr6

array([ 2,  4,  6,  8, 10])

In [68]:
# Linspace function - It gives number based on the count between start and end number
arr7=np.linspace(start=1,stop=5,num=10)
arr7

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [70]:
# reshape- we can reshape our arrays
# arr3 was (2,3)
arr3.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [72]:
# Ravel() - Flattern the array, It just create a new array it will not alter the old array
arr8=np.array([[1,2,3],[4,5,6]])
arr8.ravel()

array([1, 2, 3, 4, 5, 6])

In [74]:
# Matheactical Functions
print("arr.min():",arr.min(),"\narr.max():",arr.max(),"\narr.sum():",arr.sum())

arr.min(): 1 
arr.max(): 5 
arr.sum(): 15


In [80]:
# Now in sum() there is a concept of axis 0(columns) and axis 1(rows) for 2D arrays ex
arr9=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Axis 0:",arr9.sum(axis=0),"\nAxis 1:",arr9.sum(axis=1))

Axis 0: [12 15 18] 
Axis 1: [ 6 15 24]


In [82]:
# sqrt() - square root function, which is not an individual element function. It is a generic function means
np.sqrt(arr9)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [85]:
# std() - It is also generic one
np.std(arr9,dtype=np.float32)

np.float32(2.5819888)

In [93]:
# Basic Operations
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print("Addition:\n",a1+a2,"\nSubtraction:\n",a1-a2,"\nMultiplication:\n",a1*a2,"\nDivision:\n",a1/a2)

Addition:
 [[ 6  8]
 [10 12]] 
Subtraction:
 [[-4 -4]
 [-4 -4]] 
Multiplication:
 [[ 5 12]
 [21 32]] 
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [95]:
# We also have dot() - It do matirx Product
print("a1.dot(a2):\n",a1.dot(a2),"\na2.dot(a1):\n",a2.dot(a1))

a1.dot(a2):
 [[19 22]
 [43 50]] 
a2.dot(a1):
 [[23 34]
 [31 46]]
