In [1]:
import numpy as np

In [3]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
# Simple way to iterate through this array is just to run
for row in arr:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
# If we want to iterate over cells then
for cell in arr.flat:
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
# numpy offer a function called nditer - which allows more easy way to perform iteration
# (1) C-Order
for x in np.nditer(arr,order='C'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
# (2) Fortan Order
for x in np.nditer(arr,order='F'):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [14]:
# I want to go on fortan order but instead of cells i want to print entire column
for x in np.nditer(arr,order='F',flags=['external_loop']):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [23]:
# While iterating if i want to modify the elements lets suppose by +1 then we use flags=['readwrite]
for x in np.nditer(arr,order='C',op_flags=['readwrite']):
  x[...]=x-2
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# We can also iterate over 2 numpy arrays at a same time
arr2=np.arange(3,15,4).reshape(3,1)
arr2

array([[ 3],
       [ 7],
       [11]])

In [26]:
for x,y in np.nditer([arr,arr2]):
  print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [27]:
# From Above output we can conclude either the shapes of array should be same or one of the dimensions in one of the array should be one